[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
